create table clientes
(
    id  number GENERATED BY DEFAULT AS IDENTITY,
    nome  varchar2(255) NOT NULL,
    cpf  varchar2(11) NOT NULL,
    dt_nascimento DATE NOT NULL,
    email  VARCHAR2(100) NOT NULL unique ,
    telefone varchar2(11) not null,
    PRIMARY KEY (id)
);