create table sinistros
(
    id number GENERATED BY DEFAULT AS IDENTITY,
    descricao varchar2(255) NOT NULL,
    valor number NOT NULL,
    seguro_id number not null,
    PRIMARY KEY (id),
    foreign key (seguro_id) references seguros(id)
);