    create table pagamentos
    (
        id  number GENERATED BY DEFAULT AS IDENTITY,
        seguro_id  number NOT NULL,
        data_criacao date NOT NULL,
        dt_pagamento date,
        tipo_pagamento VARCHAR2(100) NOT NULL,
        vl_pagamento numeric not null,
        status varchar2(11) not null,
        PRIMARY KEY (id),
        foreign key (seguro_id) references seguros(id)
    );